### ISSUE TITLE
SVG not rendering

### ISSUE THREAD

**Issue by kethan** [WebReflection/jsx2tag#3] opened 2022-03-26 06:34 UTC
https://codepen.io/kethan-the-selector/pen/RwxpLgO?editors=0011

**Comment by WebReflection** [comment] 2022-03-26 15:11
Yeah, it's a bit tricky, but this works.

```js
// uhtml/jsx exports uhtml and pollutes the global
// with React.createElement and React.Fragment
import { bind, render, html, svg } from "//cdn.skypack.dev/uhtml/jsx";
const SVG = () => svg`<svg>
    <g transform="translate(20,20)">
      <text>hello</text>
    </g>
  </svg>`;

// console.log(svg)
const App = ({ name }) =>
  html`
    Hello ${name} 👋
  `;

render(
  document.body,
  <div>
    <App name="JSX" />
    <SVG />
  </div>
);
```

I'll keep this open until I find a solution I like, if a solution is even possible.

**Comment by kethan** [comment] 2022-03-27 12:54
Yes this works but if it works with jsx it would be sweet not a big issue though

**Comment by kethan** [comment] 2022-03-27 13:10
A quick question regarding wicked elements how do i have css per component kind of shadow

**Comment by WebReflection** [comment] 2022-03-27 15:20
Actually, I went [through the README](https://github.com/WebReflection/jsx2tag#features) and the issue is with the created pragma.

For SVG component you better create a pragma that uses `svg` instead of `html` utility, and confine those components in separate files. You can then import those SVG / XML components and there should be no issue.

This is more an implementation detail and surely less magic than expected, but it makes sense because it uses `html` by default, so change the export, create your own pragmas as shown in the README, and code happily ever after?

I guess this will be closed as *wontfix* then.

Regarding other unrelated topics, [please use the discussions repo](https://github.com/WebReflection/discussions/discussions) because it makes zero sense to discuss other projects in an issue about something else, but also I really have [little extra time these days](https://twitter.com/WebReflection/status/1490618596271267840), so don't expect quick come backs from me, sorry.

**Closed as completed by WebReflection** 2022-03-27 15:20 UTC
Labels: wontfix
